sudo: false
language: node_js
node_js:
  - "11"
os:
  - osx
  - linux

before_install:
  - export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  - sh -e /etc/init.d/xvfb start;
  - sleep 3;

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent
