sudo: false
language: node_js
node_js:
  - "11"

jobs:
  include:
    - os: linux
      services:
      - xvfb
    - os: osx

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9";
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent
